# Generated by Django 2.2.4 on 2019-08-20 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0002_messages_mssg_date_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectConversationRecords',
            fields=[
                ('conversation_id', models.AutoField(db_column='conversation_id', primary_key=True, serialize=False)),
                ('user_one', models.ForeignKey(db_column='user_one_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_one_direct', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(db_column='user_two_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_two_direct', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
