# Generated by Django 2.2.4 on 2019-08-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_directconversationrecords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={},
        ),
        migrations.AlterModelTable(
            name='directconversationrecords',
            table='DirectConversationRecords',
        ),
        migrations.AlterModelTable(
            name='messages',
            table='Messages',
        ),
    ]
