# Generated by Django 2.2.4 on 2019-08-20 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20190820_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='direct_conversation_id',
            field=models.ForeignKey(blank=True, db_column='direct_conversation_id', default=False, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_direct_id', to='messenger.DirectConversationRecords'),
        ),
    ]
