# Generated by Django 2.2.4 on 2019-08-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_messages_direct_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='mssg_date_stamp',
            field=models.DateTimeField(auto_now=True, db_column='mssg_date_stamp'),
        ),
    ]
