# Generated by Django 2.2.4 on 2019-08-26 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_auto_20190823_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='from_User',
            field=models.ForeignKey(db_column='from_User', on_delete=django.db.models.deletion.CASCADE, related_name='sender_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='to_User',
            field=models.ForeignKey(db_column='to_User', on_delete=django.db.models.deletion.CASCADE, related_name='receiver_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
