# Generated by Django 2.2.5 on 2019-09-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_auto_20190826_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='directconversationrecords',
            name='last_spoken_to',
            field=models.DateTimeField(auto_now=True, db_column='last_spoken_to'),
        ),
    ]
