# Generated by Django 2.2.5 on 2019-09-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_remove_contactlist_last_spoken_to'),
        ('messenger', '0008_directconversationrecords_last_spoken_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='directconversationrecords',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_conversation', to='User.contactList'),
        ),
    ]
