# Generated by Django 2.2.4 on 2019-08-20 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20190820_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='active_contact',
            field=models.BooleanField(db_column='active_contact', default=False),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_column='contact_date'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='friend',
            field=models.ForeignKey(db_column='friend_id', on_delete=django.db.models.deletion.CASCADE, related_name='friend_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='friend_ship_initiator',
            field=models.ForeignKey(db_column='friend_ship_initiator_id', on_delete=django.db.models.deletion.CASCADE, related_name='friend_initiator', to=settings.AUTH_USER_MODEL),
        ),
    ]
