# Generated by Django 2.2.4 on 2019-08-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20190820_1613'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
