# Generated by Django 2.2.5 on 2019-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20190822_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='combined_friend_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
