# Generated by Django 2.2.5 on 2019-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20190903_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='last_spoken_to',
            field=models.DateTimeField(auto_now=True, db_column='last_spoken_to'),
        ),
    ]
