# Generated by Django 2.2.5 on 2019-09-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_contactlist_last_spoken_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='last_spoken_to',
        ),
    ]
